[package]
name = "hello"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hello"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

hello_integrity = { workspace = true } 
